const Lens = {
  resina: [
    'Resina Branca',
    'Resina com Antirreflexo',
    'Resina Blue Cut',
    'Resina Foto com Antirreflexo',
    'Resina Foto Blue Cut',
    'Resina Transitions',
    'Resina Transitions com Antirreflexo',
    'Resina EXG Branca',
    'Resina EXG com Antirreflexo',
    'Resina EXG Blue Cut',
    'Resina EXG Foto com Antirreflexo',
    'Resina EXG Foto Blue Cut',
    'Resina EXG Transitions',
    'Resina EXG Transitions com Antirreflexo',
  ],
  resina161: [
    'Resina 1.61 com Antirreflexo',
    'Resina 1.61 Blue Cut',
    'Resina 1.61 EXG com Antirreflexo',
  ],
  resina167: [
    'Resina 1.67 com Antirreflexo',
    'Resina 1.67 Blue Cut',
    'Resina 1.67 EXG com Antirreflexo',
  ],
  resina170: [
    'Resina 1.70 EXG Blue Cut',
    'Resina 1.70 EXG Transitions',
    'Resina 1.70 EXG Transitions com Antirreflexo',
  ],
  policarbonato: [
    'Policarbonato Branca',
    'Policarbonato com Antirreflexo',
    'Policarbonato Blue Cut',
    'Policarbonato Foto com Antirreflexo',
    'Policarbonato Transitions',
    'Policarbonato Transitions com Antirreflexo',
    'Policarbonato EXG Branca',
    'Policarbonato EXG com Antirreflexo',
    'Policarbonato EXG Blue Cut',
    'Policarbonato EXG Foto com Antirreflexo',
    'Policarbonato EXG Transitions',
    'Policarbonato EXG Transitions com Antirreflexo',
  ],

  multResina: [
    'Mult Resina Branca',
    'Mult Resina com Antirreflexo',
    'Mult Resina Blue Cut',
    'Mult Resina Foto com Antirreflexo',
    'Mult Resina Foto Blue Cut',
    'Mult Resina Branca Surfaçada',
    'Mult Resina com Antirreflexo Surfaçada',
    'Mult Resina Blue Cut Surfaçada',
    'Mult Resina Foto com Antirreflexo Surfaçada',
    'Mult Resina Foto Blue Cut Surfaçada',
    'Mult Resina Transitions Surfaçada',
    'Mult Resina Transitions com Antirreflexo Surfaçada',
  ],
};

export default Lens;
